spring:
  application:
    name: axspring

  profiles:
    default: local

app:
  cors:
    allowed-origins:
      - http://localhost:3000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId:-}] %logger{36} - %msg%n"
