spring:
  application:
    name: backend

  profiles:
    default: local

server:
  port: 8080

app:
  cors:
    allowed-origins:
      - http://localhost:5173

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId:-}] %logger{36} - %msg%n"
